import {
  Form,
  FormGrid,
  FormLayout,
  FormTab,
  FormCollapse,
  FormItem,
  Checkbox,
  // Cascader,
  Editable,
  Input,
  InputNumber,
  // Switch,
  Password,
  PreviewText,
  Radio,
  Reset,
  Select,
  Space,
  Submit,
  // TimePicker,
  // DatePicker,
  Transfer,
  Upload,
  ArrayTable,
  ArrayCards,
} from '@formily/element-plus'

import {
  Text,
  Card,
  Switch,
  IframeBox,
  Button,
  TreeSelect,
  Cascader,
  TimePicker,
  DatePicker,
} from '@designer-renderer'

import { createSchemaField } from '@formily/vue'

// 渲染schema数据的组件
export const { SchemaField } = createSchemaField({
  components: {
    FormTab,
    IframeBox,
    Button,
    Card,
    Text,
    Form,
    FormItem,
    Select,
    TreeSelect,
    Input,
    InputNumber,
    Switch,
    DatePicker,
    Checkbox,
    Cascader,
    Editable,
    Password,
    PreviewText,
    Radio,
    Reset,
    Space,
    Submit,
    TimePicker,
    Transfer,
    Upload,
    FormGrid,
    FormLayout,
    FormCollapse,
    ArrayTable,
    ArrayCards,
  },
})
