import { createSchemaField } from '@formily/vue'

import {
  Form,
  FormGrid,
  FormLayout,
  FormTab,
  FormCollapse,
  FormItem,
  Checkbox,
  Cascader,
  Editable,
  Input,
  InputNumber,
  // Switch,
  Password,
  PreviewText,
  Radio,
  Reset,
  // Select,
  Space,
  Submit,
  TimePicker,
  DatePicker,
  Transfer,
  Upload,
  ArrayTable,
  ArrayCards,
} from '@formily/element-plus'
// import * as ElementUI from '@formily/element-plus'

import { Switch } from '@designer-renderer'

import {
  Select,
  BackgroundStyleSetter,
  BorderRadiusStyleSetter,
  BorderStyleSetter,
  BackgroundImageInput,
  BoxShadowStyleSetter,
  BoxStyleSetter,
  CollapseItem,
  ColorInput,
  CornerInput,
  DisplayStyleSetter,
  DrawerSetter,
  FlexStyleSetter,
  FontStyleSetter,
  ImageInput,
  MonacoInput,
  PositionInput,
  SizeInput,
  ValueInput,
  DataSourceSetter,
  ReactionsSetter,
  ValidatorSetter,
} from './components'

export const { SchemaField } = createSchemaField({
  components: {
    Select,
    Form,
    FormGrid,
    FormLayout,
    FormTab,
    FormCollapse,
    FormItem,
    Checkbox,
    Cascader,
    Editable,
    Input,
    InputNumber,
    Switch,
    Password,
    PreviewText,
    Radio,
    Reset,
    Space,
    Submit,
    TimePicker,
    DatePicker,
    Transfer,
    Upload,
    ArrayTable,
    ArrayCards,

    CollapseItem,
    ValueInput,
    SizeInput,
    ColorInput,
    ImageInput,
    MonacoInput,
    PositionInput,
    CornerInput,
    BackgroundImageInput,
    BackgroundStyleSetter,
    BoxStyleSetter,
    BorderStyleSetter,
    BorderRadiusStyleSetter,
    DisplayStyleSetter,
    BoxShadowStyleSetter,
    FlexStyleSetter,
    FontStyleSetter,
    DrawerSetter,
    DataSourceSetter,
    ReactionsSetter,
    ValidatorSetter,
  },
})
